import streamlit as st
import pandas as pd
import json
import time
import glob
import os

# --- 1. CONFIGURATION ---
st.set_page_config(page_title="Network Traffic Monitor", layout="wide", page_icon="🛡️")

# Base path where Docker mounts the volumes
BASE_DATA_DIR = "data"
PEERS = ["peer1", "peer2", "peer3", "peer4", "peer5"]

# --- 2. HELPER FUNCTIONS (NEW: To extract IPs from flow strings) ---
def parse_flow_key(flow_key):
    """
    Converts '192.168.1.1:1234->10.0.0.1:80/TCP' 
    into ('192.168.1.1', '10.0.0.1')
    """
    try:
        # Expected format: src:port->dst:port/PROTO
        parts = flow_key.split('->')
        src_part = parts[0]
        dst_part = parts[1]
        
        src_ip = src_part.split(':')[0]
        dst_ip = dst_part.split(':')[0]
        return src_ip, dst_ip
    except:
        return None, None

def get_latest_summary(peer_name):
    """Reads the latest JSON generated by the Python agent."""
    search_path = os.path.join(BASE_DATA_DIR, peer_name, "aggregated_flows", "summary_*.json")
    files = glob.glob(search_path)
    if not files:
        return None
    
    # Get the most recent one by modification time
    latest_file = max(files, key=os.path.getctime)
    try:
        with open(latest_file, 'r') as f:
            data = json.load(f)
            data['peer'] = peer_name
            return data
    except:
        return None

def load_data(selected_view):
    """Loads and consolidates data from selected peers."""
    consolidated = {
        'total_bytes': 0, 
        'total_packets': 0, 
        'flow_count': 0,
        'scanners': [], 
        'heavy_hitters': [],
        'ddos_victims': [] # <--- NEW FIELD FOR DDoS
    }
    
    peers_to_read = PEERS if selected_view == "Global (All Peers)" else [selected_view]
    
    # Temporary dictionary to detect DDoS: {dst_ip: {set of src_ips}}
    ddos_tracker = {}

    active_peers = 0
    for peer in peers_to_read:
        data = get_latest_summary(peer)
        if data:
            active_peers += 1
            # 1. Sum metrics
            consolidated['total_bytes'] += data.get('cms', {}).get('total_bytes', 0)
            consolidated['total_packets'] += data.get('cms', {}).get('total_packets', 0)
            consolidated['flow_count'] += data.get('hll', {}).get('cardinalities', {}).get('unique_flows', 0)
            
            # 2. Collect Scanners (HLL)
            scanners = data.get('hll', {}).get('port_scanners', [])
            for s in scanners:
                s['origin_peer'] = peer
                consolidated['scanners'].append(s)
                
            # 3. Process Heavy Hitters and search for DDoS (NEW LOGIC)
            hh = data.get('cms', {}).get('heavy_hitters_bytes', [])
            for h in hh:
                h['detected_by'] = peer
                consolidated['heavy_hitters'].append(h)
                
                # DDoS Analysis: Extract IPs from heavy hitter flow
                # If a destination IP receives heavy traffic from many sources, it is suspicious
                s_ip, d_ip = parse_flow_key(h['flow'])
                if s_ip and d_ip:
                    if d_ip not in ddos_tracker:
                        ddos_tracker[d_ip] = set()
                    ddos_tracker[d_ip].add(s_ip)

    # 4. Determine DDoS victims
    # Rule: If a destination IP receives heavy traffic from >= 3 distinct source IPs -> DDoS Alert
    for dst_ip, attackers in ddos_tracker.items():
        if len(attackers) >= 3: 
            consolidated['ddos_victims'].append({
                'victim': dst_ip,
                'attackers_count': len(attackers),
                'attackers': list(attackers)
            })

    return consolidated, active_peers

# --- 3. SIDEBAR ---
st.sidebar.title("🔧 Control Panel")
view_mode = st.sidebar.selectbox("Select View Source:", ["Global (All Peers)"] + PEERS)
st.sidebar.markdown("---")
st.sidebar.caption("Refreshing every 2 seconds...")

# --- 4. MAIN INTERFACE ---
st.title("📊 Data Center Traffic Monitor")

placeholder = st.empty()

while True:
    data, active_count = load_data(view_mode)
    
    with placeholder.container():
        # A. AGENT STATUS
        if active_count == 0:
            st.warning("⏳ Waiting for agents... (No data found yet)")
        else:
            # B. SECURITY ALERT PANEL (Scanner + DDoS)
            scanners = data['scanners']
            ddos_victims = data['ddos_victims']
            
            # Alert visualization logic
            if not scanners and not ddos_victims:
                st.success("✅ **Network Status:** Healthy (No anomalies detected)")
            else:
                # --- NEW DDoS ALERT (RED) ---
                if ddos_victims:
                    for d in ddos_victims:
                        st.error(f"🚨 **DDoS ATTACK DETECTED:** Victim `{d['victim']}` is being targeted by {d['attackers_count']} heavy flows!")
                        with st.expander(f"View attack details for {d['victim']}"):
                            st.write(f"Attackers: {', '.join(d['attackers'])}")
                
                # --- SCANNERS ALERT (YELLOW) ---
                if scanners:
                    attacker_ips = list(set([s['ip'] for s in scanners]))
                    st.warning(f"⚠️ **PORT SCANNER DETECTED:** {len(attacker_ips)} IPs are scanning network ports.")

            st.divider()

            # C. KEY METRICS
            col1, col2, col3 = st.columns(3)
            col1.metric("Active Flows (Approx)", data['flow_count'])
            col2.metric("Total Packets", f"{data['total_packets']:,}")
            
            # Byte Formatting (KB/MB/GB)
            bytes_val = data['total_bytes']
            if bytes_val > 1024**3:
                bytes_str = f"{bytes_val/1024**3:.2f} GB"
            elif bytes_val > 1024**2:
                bytes_str = f"{bytes_val/1024**2:.2f} MB"
            else:
                bytes_str = f"{bytes_val/1024:.2f} KB"
            col3.metric("Throughput", bytes_str)

            # D. HEAVY HITTERS CHART
            st.subheader("🏆 Top Bandwidth Consumers (Heavy Hitters)")
            
            if data['heavy_hitters']:
                df_hh = pd.DataFrame(data['heavy_hitters'])
                # Sort and take Top 10
                df_top = df_hh.sort_values('bytes', ascending=False).head(10)
                
                st.bar_chart(data=df_top, x='flow', y='bytes', color='detected_by')
                
                with st.expander("View Raw Flow Data"):
                    st.dataframe(df_top[['flow', 'bytes', 'detected_by']], use_container_width=True)
            else:
                st.info("Collecting traffic statistics...")

    time.sleep(2)