import streamlit as st
import pandas as pd
import json
import time
import glob
import os

# Page configuration
st.set_page_config(page_title="Network Traffic Monitor", layout="wide")

# Base path where Docker mounts the volumes
BASE_DATA_DIR = "data"
PEERS = ["peer1", "peer2", "peer3", "peer4", "peer5"]

# --- 2. LOADING FUNCTIONS ---
def get_latest_summary(peer_name):
    """Reads the latest JSON generated by the Python agent."""
    # Path: data/peerX/aggregated_flows/summary_*.json
    search_path = os.path.join(BASE_DATA_DIR, peer_name, "aggregated_flows", "summary_*.json")
    files = glob.glob(search_path)
    if not files:
        return None
    
    # Take most recent one
    latest_file = max(files, key=os.path.getctime)
    try:
        with open(latest_file, 'r') as f:
            data = json.load(f)
            data['peer'] = peer_name
            return data
    except:
        return None

def load_data(selected_view):
    consolidated = {
        'total_bytes': 0, 'total_packets': 0, 'flow_count': 0,
        'scanners': [], 'heavy_hitters': []
    }
    
    peers_to_read = PEERS if selected_view == "Global (All Peers)" else [selected_view]
    
    active_peers = 0
    for peer in peers_to_read:
        data = get_latest_summary(peer)
        if data:
            active_peers += 1
            # Metrics calculated by CMS/HLL
            consolidated['total_bytes'] += data.get('cms', {}).get('total_bytes', 0)
            consolidated['total_packets'] += data.get('cms', {}).get('total_packets', 0)
            consolidated['flow_count'] += data.get('hll', {}).get('cardinalities', {}).get('unique_flows', 0)
            
            # Security alerts (HLL)
            scanners = data.get('hll', {}).get('port_scanners', [])
            for s in scanners:
                s['origin_peer'] = peer # Know who detected it
                consolidated['scanners'].append(s)
                
            # Heavy Hitters (CMS)
            hh = data.get('cms', {}).get('heavy_hitters_bytes', [])
            for h in hh:
                h['detected_by'] = peer
                consolidated['heavy_hitters'].append(h)
                
    return consolidated, active_peers

# --- 3. LATERAL SECTION ---
st.sidebar.title("🔧 Control Panel")
view_mode = st.sidebar.selectbox("Select View Source:", ["Global (All Peers)"] + PEERS)
st.sidebar.markdown("---")
st.sidebar.caption("Refreshing every 2 seconds...")

# --- 4. PRINCIPAL INTERFACE ---
st.title("📊 Data Center Traffic Monitor")

# Placeholder for real-time updates
placeholder = st.empty()

while True:
    # Load fresh data
    data, active_count = load_data(view_mode)
    
    with placeholder.container():
        # A. STATE PANEL
        if active_count == 0:
            st.warning("⏳ Waiting for agents... (No data found yet)")
        else:
            # B. ALERT PANEL (Based on HLL Scanners)
            scanners = data['scanners']
            if scanners:
                # Format attackers list
                attacker_ips = list(set([s['ip'] for s in scanners]))
                st.warning(f"⚠️ **SCANNER DETECTED:** {len(attacker_ips)} IPs are scanning ports: {', '.join(attacker_ips)}")
            else:
                st.success("✅ **Network Status:** Healthy (No anomalies detected)")

            # C. KEY METRICS (Based on CMS Totals)
            col1, col2, col3 = st.columns(3)
            col1.metric("Active Flows (Approx)", data['flow_count'])
            col2.metric("Total Packets", f"{data['total_packets']:,}")
            
            # Format bytes
            bytes_val = data['total_bytes']
            if bytes_val > 1024**3:
                bytes_str = f"{bytes_val/1024**3:.2f} GB"
            else:
                bytes_str = f"{bytes_val/1024**2:.2f} MB"
            col3.metric("Throughput", bytes_str)

            # D. VISUALIZATIONS (Based on CMS Heavy Hitters)
            st.subheader("🏆 Top Bandwidth Consumers (Heavy Hitters)")
            
            if data['heavy_hitters']:
                df_hh = pd.DataFrame(data['heavy_hitters'])
                # Order globally and take Top 10
                df_top = df_hh.sort_values('bytes', ascending=False).head(10)
                
                # (Flow vs Bytes)
                st.bar_chart(data=df_top, x='flow', y='bytes', color='detected_by')
                
                # E. DETAILED TRAFFIC TABLE
                with st.expander("View Raw Flow Data"):
                    st.dataframe(
                        df_top[['flow', 'bytes', 'detected_by']],
                        width='stretch'
                    )
            else:
                st.info("Collecting traffic statistics...")

    # Polling interval (1-2 seconds)
    time.sleep(2)